image: php:7.2


stages:
  - phpunit
  - syntax_check



phpunit:
  stage: phpunit
  script:
    - apt-get update && apt-get install -y unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
    - vendor/bin/phpunit

syntax_check:
  stage: syntax_check
  script:
    - find ./src/* -name "*.php" -print0 | xargs -n 1 -0 php -l;
    - find ./tests/* -name "*.php" -print0 | xargs -n 1 -0 php -l;

